name: Deploy to GCP

on:
  push:
    branches:
      - master  # Change this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Google Cloud SDK
      run: |
        echo "Installing Google Cloud SDK..."
        curl -sSL https://sdk.cloud.google.com | bash
        exec -l $SHELL

    - name: Set up Google Cloud credentials
      run: |
        echo '{
            "type": "service_account",
            "project_id": "physiotherapistadmin",
            "private_key_id": "46949ae1e1356c7ba6189844bd65ceb7017193f3",
            "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDCi4c+qP2xJx/L\niQPEpwx9med9aMQ6zuAjYi54JKnSKwWHwPSWlQY44mH3ZN00/0D7rHvqayeyJlYW\n7YWYcQ9VmLw2sXxdZUb9w7PjGHXx6roBA+61tMwZ8grCDqsWbkVGG+R+7yubJtpu\ndXLFbGFX6MeOZSpHH2v2MDhex+CAOMqJAmMZZcXLy6IhNKRP5dQqkJtYRiMYAnoy\nZIukEBQ8AqJjsS+HAhKMnxdaPSdENHgWaHUvgXYh6JFCzehyNBs7z66Hzp9vxeXj\ncMTDAZgSI2dzmU9H9b92J7wFSu/i/5CBQLmtrKpHHSof5Wp4Xm58wnyTsylMeoEF\nIGO1ngeXAgMBAAECggEAAIHysWQpfUvX1mUeIGY7Lxy2sOoUEP83MIByFJgr5UN9\neTQ0ryvmX0Gf9dBKj3fXCJETpbHv4ZQeB2NJRPOOka+bVh0ycN/xxnm7P21x6Vau\nc5A6EDlPiwXJp2X4Zk+VWLB78STYnUgFq+IckY1N17fgxWtYJ+VaF8NackzdNhhu\nqymDsSUsHs2lF0oaSAh1v5sxRBf4PvQIAOfLtJAvPg4Pz8otTN1fK0rdpBCKj7WH\nODr7Hy0W7LLSIPAN9SyBD2Hr6954lKSigZVFCIVGCVwo/9Nzu6zxY5bmJBl5JVNE\nJKU/PhZDL90CpRPDBG8WIIVQZhN6HZt47XvhlFnBeQKBgQDJgUg5Zdu/pF2mw0MD\npsQk9fBRmRFGIN8CB0TgAbzxCAPWFFXYqI225V7sr++hceSMTMJXLjQpEji44sTb\noSgqaWrM4203nmIkzIkqOgOuGjca+GO4AXw9g3VJeoEt3S42AGQIPG8IZEEd6ko/\nJLg9l6pih9evwyTnPN6nkFiOpQKBgQD3KGONBJWaZqiGsX1/hZbIjooF80BU2Mg2\nZFAo2eGmlljShUS/mhR+lrsG1vFDk00Il/Hw248FhNcHJWAJewWaKUB/Jgnm5ga2\nSKTPPyz8e18JIjTBAJjZen/zSv3Jz05oG/lOIqMGAIF2XupfbnD0GlQa9ZZSfHo6\nCOrPQrYEiwKBgDdgw1Oa7bCWYHKDOTiYrVEnEfuq4HdwczlgfApAEAgB1uQPxKP9\ndqzsDpFnrKim31O7iLFi7kzXSCVvlQBzItG9FO/oFMzzRy+r0op7VSWU6M4Ns4IP\nTnCtXx9pfnT3U0reAp/M1ArvWoH5MJx33/Z1ZwsbICiardqq/Nn6LoxNAoGAA8KM\niSepsvie1bW7iAYbPh/U/7QspV3K5fDuu0BdS3B8F2/JlPSeHTLj033Pm8yQ3nGZ\nT6W3bkkQEF7EMEC73BWGkqice/PB5GIEh9aZM5oY3wWzMcB1ktFnQudAJyLNOY47\nY7HpMv0s+wUEocEHXN9Nqj9UMxsLrPhXwiFsrXMCgYEAqVHQDXxc4rBAZBc4Yhhn\nivf6KM+OO79aCYLjIO9MTZxw2U55rAh8Vo7aeJLvFG4dY1HRLmQFNL1RJiZXnLZ/\nzIb0tPS79VrAtxSAazD5X90U6m5BoSlp6KCTY+652S1ts/WpdKZnvilnoWKmf4Vq\nYLBrl/9hGMye6kBbhcOz/7M=\n-----END PRIVATE KEY-----\n",
            "client_email": "physiotherapistadmin@appspot.gserviceaccount.com",
            "client_id": "106507321155864436890",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/physiotherapistadmin%40appspot.gserviceaccount.com",
            "universe_domain": "googleapis.com"
        }' > gcloud-service-key.json

    - name: Authenticate to Google Cloud
      run: |
        gcloud auth activate-service-account --key-file=gcloud-service-key.json

    - name: Deploy to Google App Engine
      run: |
        gcloud config set project physiotherapistadmin
        gcloud app deploy --quiet
